variable "project_name" {}
variable "app_image" {}
variable "app_port" {}
variable "fargate_cpu" {}
variable "fargate_memory" {}
variable "region" {}
variable "app_count" {}
variable "alb_target_group_arn" {}
variable "alb_security_group_id" {}
variable "private_subnet_az1_id" {}
variable "private_subnet_az2_id" {}